### ISSUE TITLE
Disallow impossible resource configurations for notebooks

### ISSUE THREAD

**Issue by brendangadd** [StatCan/kubeflow-manifest#1]
In the notebook server creation view, users can specify configuration that is impossible for the cluster to fulfill. For example, the GPU dropdown list goes up to eight GPUs vs. our actual maximum of one.

Modify displayed values and add validation to help prevent this from occurring.

Note that this doesn't have to dynamically adapt to our node pool configuration; it can be statically maintained for our installation.

**Comment by sylus** [comment]
This is done now and can be deployed during the week.

https://github.com/StatCan/kubeflow-manifest/commit/5fa94c48f81cc3c2a8f225132c5da2956c4c1b62
