### ISSUE TITLE
Confusing error when authentication fails

### ISSUE THREAD

**Issue by brendangadd** [StatCan/kubeflow-manifest#10]
When authentication fails (e.g. when a user successfully authenticates an Azure account that isn't in our tenant), they get a cryptic error message on a blank page: `Missing url parameter: code`.

Potential solutions, in order of preference:
1. Have the authentication provider enforce authentication of an account **in our tenant** before redirecting back to an application
2. Display a user-friendly view that contains sufficient information for the user to resolve the issue without support

**Comment by zachomedia** [comment]
This has been accomplished with a tweak on solution 1. 

Azure Active Directory has a flag we can pass when sending the user for login which informs AAD to always show the account selection screen, which should alleviate it automatically sending users to Kubeflow when logged into another account.

https://github.com/zachomedia/oidc-authservice/commit/e6b4a0ebe9a0722c91b3e2791053be44d5395987#diff-31a4a7824225629df071a1cba8b785d5R81
