### ISSUE TITLE
Remove "base" image from KF menu (kustomize)

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/kubeflow-manifest#2]
I think the base image is really for building the real images, and shouldn't be used in practice (only used to derive other images.) I kinda regret separating the base and minimal images in retrospect.

**therefore, maybe we should remove it from the menu**, this would deal with issues like this one.

https://github.com/StatCan/kubeflow-containers/issues/19

**Comment by sylus** [comment]
Done and made the adjustment!
