### ISSUE TITLE
feat(kfam): create deployment from StatCan/Kubeflow

### ISSUE THREAD

**Issue by Souheil-Yazji** [StatCan/kubeflow-manifest#335]
blocked by: [StatCan/aaw/#1727](https://github.com/StatCan/aaw/issues/1727)
requirement for : [StatCan/aaw/#1699](https://github.com/StatCan/aaw/issues/1699)
Having the ability to extend the Kubeflow Access Management module seems inevitable. To add access control and action [this issue](https://github.com/StatCan/kubeflow/pull/138) we'll need to build and deploy our own kfam image. 

- [ ] Need to update the deployment after kf1.7 code is available in dev

Completed by https://github.com/StatCan/aaw-kubeflow-manifests/pull/338

**Comment by chuckbelisle** [comment]
This is for Dev cluster only at this time
