### ISSUE TITLE
Update central dashboard links with our own content

### ISSUE THREAD

**Issue by brendangadd** [StatCan/kubeflow-manifest#81]
### Background
* Need to replace [upstream links configmap][] with one that has our own structure/content
* @saffaalvi has an updated configmap, but needs to know how to add it to our manifests
* @sylus to assist

### Todo
* @sylus: Create a PR that demonstrates how to add our own configmap via our manifests
* @saffaalvi: Take that PR and update with your configmap content
* Deploy
* @saffaalvi: Share approach with the team so we know how this is done with the new manifest layout

[upstream links configmap]: https://github.com/kubeflow/manifests/blob/master/common/centraldashboard/base/links-configmap.yaml

**Comment by sylus** [comment]
Linked the P.R. showing how this works.
